import "./globals.css";
import Navbar from "./components/Navbar/Navbar";
// import { ContextProvider } from "./cartContext/page";
import { ContextProvider } from "./cartContext/page";
import Footer from "./components/Footer/page";
import HideOnAuth from "./components/HideOnAuth";
export const metadata = {
  title: "Bashi-tech",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <ContextProvider>
          {/* <Navbar /> */}
          <HideOnAuth>{<Navbar />} </HideOnAuth>
          {children}
          {/* <Footer /> */}

          <HideOnAuth>
            <Footer />
          </HideOnAuth>
        </ContextProvider>
      </body>
    </html>
  );
}
